project:
  type: book

book:
  title: "Bioacoustics work in the Barthelmess Lab"
  author: "Erika Barthelmess"
  date: "6/18/2024"
  chapters:
    - index.qmd
    - intro-sound.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


editor: visual

